version: '2'

services:
  webserver:
    build: ./docker/webserver
    image: apache-php
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./vhosts:/etc/apache2/sites-available
      - ./vhosts:/etc/apache2/sites-enabled
    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db_dev

